CREATE DATABASE ORG;

USE ORG;

CREATE TABLE DEPT1(
	EMPID INT PRIMARY KEY,
    NAME VARCHAR(255),
    ROLE VARCHAR(255)
);

INSERT INTO DEPT1 (EMPID, NAME, ROLE) VALUES
	(1, "A","ENGINEER"),
    (2, "B", "SALESMAN"),
    (3, "C", "MANAGER"),
    (4, "D", "SALESMAN"),
    (5, "E", "ENGINEER");
    
SELECT * FROM DEPT1;

CREATE TABLE DEPT2 (
	EMPID INT PRIMARY KEY,
    NAME CHAR(25),
    ROLE CHAR(25)
);
DROP TABLE DEPT2;

INSERT INTO DEPT2 (EMPID, NAME, ROLE) VALUES
	(3, "C", "MANAGER"),
    (6, "F", "MARKETING"),
    (7, "G", "SALESMAN");
    
SELECT * FROM DEPT2;

-- SET OPERATIONS

-- LIST OUT ALL THE EMPLOYEES IN THE COMPANY
SELECT * FROM DEPT1
UNION 
SELECT * FROM DEPT2;

-- LIST OUT ALL THE EMPLOYEES FROM ALL THE DEPARTMENTS WHO WORK AS SALESMAN
SELECT * FROM DEPT1 WHERE ROLE = "SALESMAN"
UNION
SELECT * FROM DEPT2 WHERE ROLE = "SALESMAN";

-- UNION SET OPERATION
-- LIST OUT ALL THE EMPLOYEESS WHO WORK FOR BOTH THE DEPARTMENTS
-- THIS WILL GIVE A SINGLE COLUMN OUTPUT
SELECT DEPT1.* FROM DEPT1 INNER JOIN DEPT2 USING (EMPID);

-- INTERSECTION SET OPERATION
-- WHILE THIS WILL RESULT IN THE INCREASE IN NUMBER OF COLUMNS
SELECT * FROM DEPT1 INNER JOIN DEPT2 USING(EMPID);

-- MINUS SET OPERATIONS
-- LIST OUT ALL THE EMPLOYEES WORKING IN THE DEPT1 BUT NOT IN DEPT2
SELECT DEPT1.* FROM DEPT1 LEFT JOIN DEPT2 USING(EMPID)
WHERE DEPT2.EMPID IS NULL;